services:
  db:
    image: postgres:15-alpine
    container_name: rag_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rag_chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  weaviate:
    image: semitechnologies/weaviate:1.24.1
    container_name: rag_weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: rag_mlflow
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./artifacts --host 0.0.0.0
    volumes:
      - mlflow_data:/mlflow

  backend:
    build: .
    container_name: rag_backend
    depends_on:
      db:
        condition: service_healthy
      weaviate:
        condition: service_started
      mlflow:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rag_chat
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - WEAVIATE_URL=http://weaviate:8080
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./data/docs:/app/data/docs

  frontend:
    build: ./frontend
    container_name: rag_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NODE_ENV=production

volumes:
  postgres_data:
  weaviate_data:
  mlflow_data:
